# Generated by Django 4.1.3 on 2022-11-13 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasks_organization', models.CharField(max_length=200)),
                ('tasks_full_name', models.CharField(max_length=200)),
                ('tasks_tel_number', models.CharField(max_length=200)),
                ('tasks_email', models.EmailField(max_length=254)),
                ('tasks_source', models.CharField(max_length=200)),
                ('tasks_theme_letters', models.CharField(max_length=200)),
                ('tasks_stages', models.CharField(max_length=200)),
                ('tasks_requested_equipment', models.CharField(max_length=200)),
                ('tasks_more_info', models.TextField()),
                ('tasks_name_offer', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
